#!/bin/sh

source "scripts/sh/color.sh"

ConfigFile=config

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  SetInfoColor
  cat "scripts/docs/add-case-manual.txt"
  exit 0
fi

if ! test -f "$ConfigFile"; then
  echo "Error: ./config file not found"
  exit 1
fi

eval "$(cat $ConfigFile)"

if [ -z "$Problem" ]; then
  echo "Error: Problem variable not found in ./config file"
  exit 1
fi

CaseId=0
while test -f "workspace/$Problem/cases/$CaseId.in"
do
  CaseId=$((CaseId+1))
done

echo "Adding case $CaseId..."
code "workspace/$Problem/cases/$CaseId.out"
code "workspace/$Problem/cases/$CaseId.in"
