#!/bin/sh

Lang="go"
Problem=""
ConfigFile=config

LanguageGiven="false"
SetLanguage () {
  if [ "$LanguageGiven" = "true" ]; then
    echo "ERROR: Language given multiple times, but it must be given at most once."
    exit 1
  else
    Lang="$1"
  fi
  LanguageGiven="true"
}


while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      cat "docs/create-manual.txt"
      exit 0
      ;;

    -l|--lang)
      shift
      SetLanguage "$1"
      shift
      ;;

    *)
      echo "Default"
      if [ -z "$Problem" ]; then
        Problem="$1"
        shift
      else
        echo "ERROR: Could not parse parameter: $1"
        exit 1
      fi
      ;;
  esac
done


echo "Lang=$Lang"
echo "Problem=$Problem"

if ! echo "$Lang" | grep -Eq "^cpp|go$" ; then
  echo "ERROR: Invalid language $Lang"
  exit 1
fi

if [ -d "workspace/$Problem" ]
then
	echo "ERROR: Directory workspace/$Problem already exists"
	exit 1
fi

mkdir "workspace/$Problem"
mkdir "workspace/$Problem/cases"

cp "notebook/$Lang/template.go" "workspace/$Problem/main.go"
touch "workspace/$Problem/cases/0.in"
touch "workspace/$Problem/cases/0.out"

code "workspace/$Problem/main.go"
code "workspace/$Problem/cases/0.in"
code "workspace/$Problem/cases/0.out"

echo "Lang=$Lang" > "$ConfigFile"
echo "Problem=$Problem" >> "$ConfigFile"
echo "CaseId=0" >> "$ConfigFile"
