#!/bin/sh

if [ "$1" = "-h" -o "$1" = "--help" ]; then
  cat "docs/create-manual.txt"
  exit 0
fi

Problem="$1"
ConfigFile=config

if [ -d "workspace/$Problem" ]
then
	echo "ERROR: Directory workspace/$Problem already exists"
	exit 1
fi

mkdir "workspace/$Problem"
mkdir "workspace/$Problem/cases"

cp "notebook/template.go" "workspace/$Problem/main.go"
touch "workspace/$Problem/cases/0.in"
touch "workspace/$Problem/cases/0.out"

code "workspace/$Problem/main.go"
code "workspace/$Problem/cases/0.in"
code "workspace/$Problem/cases/0.out"

echo "Problem=$Problem" > "$ConfigFile"
echo "CaseId=0" >> "$ConfigFile"
