#!/bin/sh

. scripts/sh/color.sh

ConfigFile=config
eval $(cat $ConfigFile)

if [ "$1" = "-h" -o "$1" = "--help" ]; then
  ./scripts/sh/docs/show-open-manual.sh
  exit 0
fi

if [ ! -z "$1" ]; then
  CaseId="$1"
fi

if [ -z "$CaseId" ]; then
  EchoError "CaseId not given as a parameter and is not present in the ./config file."
  exit 1
fi

INPUT_FILE="workspace/$Problem/cases/$CaseId.in"
OUTPUT_FILE="workspace/$Problem/cases/$CaseId.out"

if [ ! -f "$INPUT_FILE" ]; then
  EchoError  "Input file not found: $INPUT_FILE"
  exit 1
fi

if ! command -v "code" > /dev/null 2>&1
then
  ./scripts/sh/docs/show-error-code-not-found.sh
  exit 1
else
  code $INPUT_FILE

  if [ -f "$OUTPUT_FILE" ]; then
    code $OUTPUT_FILE
  fi
fi
